/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: {
          surface: 'var(--color-bg-surface)',
          'surface-raised': 'var(--color-bg-surface-raised)',
          primary: 'var(--color-bg-primary)',
          'primary-hover': 'var(--color-bg-primary-hover)',
          'primary-pressed': 'var(--color-bg-primary-pressed)',
          'primary-subtle': 'var(--color-bg-primary-subtle)',
          disabled: 'var(--color-bg-disabled)',
          success: 'var(--color-bg-success)',
          warning: 'var(--color-bg-warning)',
          critical: 'var(--color-bg-critical)',
        },
        text: {
          DEFAULT: 'var(--color-text-default)',
          muted: 'var(--color-text-muted)',
          primary: 'var(--color-text-primary)',
          disabled: 'var(--color-text-disabled)',
          'on-primary': 'var(--color-text-on-primary)',
          success: 'var(--color-text-success)',
          warning: 'var(--color-text-warning)',
          critical: 'var(--color-text-critical)',
        },
        border: {
          DEFAULT: 'var(--color-border-default)',
          primary: 'var(--color-border-primary)',
          disabled: 'var(--color-border-disabled)',
          critical: 'var(--color-border-critical)',
        },
      },
      spacing: {
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        7: 'var(--spacing-7)',
        8: 'var(--spacing-8)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        xxl: 'var(--radius-xxl)',
        full: 'var(--radius-fully-round)',
      },
      borderWidth: {
        none: 'var(--border-width-none)',
        thin: 'var(--border-width-thin)',
        DEFAULT: 'var(--border-width-default)',
        thick: 'var(--border-width-thick)',
      },
      width: {
        xs: 'var(--size-xs)',
        sm: 'var(--size-sm)',
        md: 'var(--size-md)',
        lg: 'var(--size-lg)',
        xl: 'var(--size-xl)',
        xxl: 'var(--size-xxl)',
        xxxl: 'var(--size-xxxl)',
        xxxxl: 'var(--size-xxxxl)',
        xxxxxl: 'var(--size-xxxxxl)',
      },
      height: {
        xs: 'var(--size-xs)',
        sm: 'var(--size-sm)',
        md: 'var(--size-md)',
        lg: 'var(--size-lg)',
        xl: 'var(--size-xl)',
        xxl: 'var(--size-xxl)',
        xxxl: 'var(--size-xxxl)',
        xxxxl: 'var(--size-xxxxl)',
        xxxxxl: 'var(--size-xxxxxl)',
      },
      fontSize: {
        'display-lg': 'var(--font-size-display-lg)',
        'headline-lg': 'var(--font-size-headline-lg)',
        'headline-md': 'var(--font-size-headline-md)',
        'title-lg': 'var(--font-size-title-lg)',
        'title-md': 'var(--font-size-title-md)',
        'body-lg': 'var(--font-size-body-lg)',
        'body-md': 'var(--font-size-body-md)',
        'label-lg': 'var(--font-size-label-lg)',
        'label-md': 'var(--font-size-label-md)',
      },
    },
  },
  plugins: [],
};
